import { Game } from './types'

// Jogos da fase de grupos — Copa do Mundo 2026
// Horários em BRT (UTC-3, horário de Brasília).
// Fontes: FIFA, ESPN, CBS Sports, NBC Sports (abril 2026).
export const GAMES: Game[] = [

  // ── Grupo A: México, África do Sul, Coreia do Sul, Tchéquia ─────────────
  {
    id: 'gA01',
    homeTeam: 'México',
    awayTeam: 'África do Sul',
    homeFlag: '🇲🇽',
    awayFlag: '🇿🇦',
    date: '2026-06-11',
    time: '16:00',
    venue: 'Estadio Azteca, Cidade do México',
    group: 'Grupo A',
    phase: 'grupo',
  },
  {
    id: 'gA02',
    homeTeam: 'Coreia do Sul',
    awayTeam: 'Tchéquia',
    homeFlag: '🇰🇷',
    awayFlag: '🇨🇿',
    date: '2026-06-11',
    time: '23:00',
    venue: 'Estadio Akron, Guadalajara',
    group: 'Grupo A',
    phase: 'grupo',
  },
  {
    id: 'gA03',
    homeTeam: 'Tchéquia',
    awayTeam: 'África do Sul',
    homeFlag: '🇨🇿',
    awayFlag: '🇿🇦',
    date: '2026-06-18',
    time: '13:00',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    group: 'Grupo A',
    phase: 'grupo',
  },
  {
    id: 'gA04',
    homeTeam: 'México',
    awayTeam: 'Coreia do Sul',
    homeFlag: '🇲🇽',
    awayFlag: '🇰🇷',
    date: '2026-06-19',
    time: '00:00',
    venue: 'Estadio Akron, Guadalajara',
    group: 'Grupo A',
    phase: 'grupo',
  },
  {
    id: 'gA05',
    homeTeam: 'Tchéquia',
    awayTeam: 'México',
    homeFlag: '🇨🇿',
    awayFlag: '🇲🇽',
    date: '2026-06-24',
    time: '22:00',
    venue: 'Estadio Azteca, Cidade do México',
    group: 'Grupo A',
    phase: 'grupo',
  },
  {
    id: 'gA06',
    homeTeam: 'África do Sul',
    awayTeam: 'Coreia do Sul',
    homeFlag: '🇿🇦',
    awayFlag: '🇰🇷',
    date: '2026-06-24',
    time: '22:00',
    venue: 'Estadio BBVA, Monterrey',
    group: 'Grupo A',
    phase: 'grupo',
  },

  // ── Grupo B: Canadá, Suíça, Qatar, Bósnia-Herzegovina ──────────────────
  {
    id: 'gB01',
    homeTeam: 'Canadá',
    awayTeam: 'Bósnia-Herzegovina',
    homeFlag: '🇨🇦',
    awayFlag: '🇧🇦',
    date: '2026-06-12',
    time: '16:00',
    venue: 'BMO Field, Toronto',
    group: 'Grupo B',
    phase: 'grupo',
  },
  {
    id: 'gB02',
    homeTeam: 'Qatar',
    awayTeam: 'Suíça',
    homeFlag: '🇶🇦',
    awayFlag: '🇨🇭',
    date: '2026-06-13',
    time: '16:00',
    venue: "Levi's Stadium, San Francisco",
    group: 'Grupo B',
    phase: 'grupo',
  },
  {
    id: 'gB03',
    homeTeam: 'Suíça',
    awayTeam: 'Bósnia-Herzegovina',
    homeFlag: '🇨🇭',
    awayFlag: '🇧🇦',
    date: '2026-06-18',
    time: '16:00',
    venue: 'SoFi Stadium, Los Angeles',
    group: 'Grupo B',
    phase: 'grupo',
  },
  {
    id: 'gB04',
    homeTeam: 'Canadá',
    awayTeam: 'Qatar',
    homeFlag: '🇨🇦',
    awayFlag: '🇶🇦',
    date: '2026-06-18',
    time: '19:00',
    venue: 'BC Place, Vancouver',
    group: 'Grupo B',
    phase: 'grupo',
  },
  {
    id: 'gB05',
    homeTeam: 'Suíça',
    awayTeam: 'Canadá',
    homeFlag: '🇨🇭',
    awayFlag: '🇨🇦',
    date: '2026-06-24',
    time: '16:00',
    venue: 'BC Place, Vancouver',
    group: 'Grupo B',
    phase: 'grupo',
  },
  {
    id: 'gB06',
    homeTeam: 'Bósnia-Herzegovina',
    awayTeam: 'Qatar',
    homeFlag: '🇧🇦',
    awayFlag: '🇶🇦',
    date: '2026-06-24',
    time: '16:00',
    venue: 'Lumen Field, Seattle',
    group: 'Grupo B',
    phase: 'grupo',
  },

  // ── Grupo C: Brasil, Marrocos, Haiti, Escócia ───────────────────────────
  {
    id: 'gC01',
    homeTeam: 'Brasil',
    awayTeam: 'Marrocos',
    homeFlag: '🇧🇷',
    awayFlag: '🇲🇦',
    date: '2026-06-13',
    time: '19:00',
    venue: 'MetLife Stadium, Nova York/NJ',
    group: 'Grupo C',
    phase: 'grupo',
  },
  {
    id: 'gC02',
    homeTeam: 'Haiti',
    awayTeam: 'Escócia',
    homeFlag: '🇭🇹',
    awayFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    date: '2026-06-13',
    time: '22:00',
    venue: 'Gillette Stadium, Boston',
    group: 'Grupo C',
    phase: 'grupo',
  },
  {
    id: 'gC03',
    homeTeam: 'Escócia',
    awayTeam: 'Marrocos',
    homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    awayFlag: '🇲🇦',
    date: '2026-06-19',
    time: '19:00',
    venue: 'Gillette Stadium, Boston',
    group: 'Grupo C',
    phase: 'grupo',
  },
  {
    id: 'gC04',
    homeTeam: 'Brasil',
    awayTeam: 'Haiti',
    homeFlag: '🇧🇷',
    awayFlag: '🇭🇹',
    date: '2026-06-19',
    time: '22:00',
    venue: 'Lincoln Financial Field, Filadélfia',
    group: 'Grupo C',
    phase: 'grupo',
  },
  {
    id: 'gC05',
    homeTeam: 'Escócia',
    awayTeam: 'Brasil',
    homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    awayFlag: '🇧🇷',
    date: '2026-06-24',
    time: '19:00',
    venue: 'Hard Rock Stadium, Miami',
    group: 'Grupo C',
    phase: 'grupo',
  },
  {
    id: 'gC06',
    homeTeam: 'Marrocos',
    awayTeam: 'Haiti',
    homeFlag: '🇲🇦',
    awayFlag: '🇭🇹',
    date: '2026-06-24',
    time: '19:00',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    group: 'Grupo C',
    phase: 'grupo',
  },

  // ── Grupo D: EUA, Paraguai, Austrália, Turquia ──────────────────────────
  {
    id: 'gD01',
    homeTeam: 'EUA',
    awayTeam: 'Paraguai',
    homeFlag: '🇺🇸',
    awayFlag: '🇵🇾',
    date: '2026-06-12',
    time: '22:00',
    venue: 'SoFi Stadium, Los Angeles',
    group: 'Grupo D',
    phase: 'grupo',
  },
  {
    id: 'gD02',
    homeTeam: 'Austrália',
    awayTeam: 'Turquia',
    homeFlag: '🇦🇺',
    awayFlag: '🇹🇷',
    date: '2026-06-14',
    time: '01:00',
    venue: 'BC Place, Vancouver',
    group: 'Grupo D',
    phase: 'grupo',
  },
  {
    id: 'gD03',
    homeTeam: 'EUA',
    awayTeam: 'Austrália',
    homeFlag: '🇺🇸',
    awayFlag: '🇦🇺',
    date: '2026-06-19',
    time: '16:00',
    venue: 'Lumen Field, Seattle',
    group: 'Grupo D',
    phase: 'grupo',
  },
  {
    id: 'gD04',
    homeTeam: 'Turquia',
    awayTeam: 'Paraguai',
    homeFlag: '🇹🇷',
    awayFlag: '🇵🇾',
    date: '2026-06-20',
    time: '01:00',
    venue: "Levi's Stadium, San Francisco",
    group: 'Grupo D',
    phase: 'grupo',
  },
  {
    id: 'gD05',
    homeTeam: 'Turquia',
    awayTeam: 'EUA',
    homeFlag: '🇹🇷',
    awayFlag: '🇺🇸',
    date: '2026-06-25',
    time: '23:00',
    venue: 'SoFi Stadium, Los Angeles',
    group: 'Grupo D',
    phase: 'grupo',
  },
  {
    id: 'gD06',
    homeTeam: 'Paraguai',
    awayTeam: 'Austrália',
    homeFlag: '🇵🇾',
    awayFlag: '🇦🇺',
    date: '2026-06-25',
    time: '23:00',
    venue: "Levi's Stadium, San Francisco",
    group: 'Grupo D',
    phase: 'grupo',
  },

  // ── Grupo E: Alemanha, Curaçao, Costa do Marfim, Equador ────────────────
  {
    id: 'gE01',
    homeTeam: 'Alemanha',
    awayTeam: 'Curaçao',
    homeFlag: '🇩🇪',
    awayFlag: '🇨🇼',
    date: '2026-06-14',
    time: '14:00',
    venue: 'NRG Stadium, Houston',
    group: 'Grupo E',
    phase: 'grupo',
  },
  {
    id: 'gE02',
    homeTeam: 'Costa do Marfim',
    awayTeam: 'Equador',
    homeFlag: '🇨🇮',
    awayFlag: '🇪🇨',
    date: '2026-06-14',
    time: '20:00',
    venue: 'Lincoln Financial Field, Filadélfia',
    group: 'Grupo E',
    phase: 'grupo',
  },
  {
    id: 'gE03',
    homeTeam: 'Alemanha',
    awayTeam: 'Costa do Marfim',
    homeFlag: '🇩🇪',
    awayFlag: '🇨🇮',
    date: '2026-06-20',
    time: '17:00',
    venue: 'BMO Field, Toronto',
    group: 'Grupo E',
    phase: 'grupo',
  },
  {
    id: 'gE04',
    homeTeam: 'Equador',
    awayTeam: 'Curaçao',
    homeFlag: '🇪🇨',
    awayFlag: '🇨🇼',
    date: '2026-06-20',
    time: '21:00',
    venue: 'Arrowhead Stadium, Kansas City',
    group: 'Grupo E',
    phase: 'grupo',
  },
  {
    id: 'gE05',
    homeTeam: 'Alemanha',
    awayTeam: 'Equador',
    homeFlag: '🇩🇪',
    awayFlag: '🇪🇨',
    date: '2026-06-25',
    time: '17:00',
    venue: 'MetLife Stadium, Nova York/NJ',
    group: 'Grupo E',
    phase: 'grupo',
  },
  {
    id: 'gE06',
    homeTeam: 'Costa do Marfim',
    awayTeam: 'Curaçao',
    homeFlag: '🇨🇮',
    awayFlag: '🇨🇼',
    date: '2026-06-25',
    time: '17:00',
    venue: 'Lincoln Financial Field, Filadélfia',
    group: 'Grupo E',
    phase: 'grupo',
  },

  // ── Grupo F: Holanda, Japão, Tunísia, Suécia ────────────────────────────
  {
    id: 'gF01',
    homeTeam: 'Holanda',
    awayTeam: 'Japão',
    homeFlag: '🇳🇱',
    awayFlag: '🇯🇵',
    date: '2026-06-14',
    time: '17:00',
    venue: 'AT&T Stadium, Dallas',
    group: 'Grupo F',
    phase: 'grupo',
  },
  {
    id: 'gF02',
    homeTeam: 'Suécia',
    awayTeam: 'Tunísia',
    homeFlag: '🇸🇪',
    awayFlag: '🇹🇳',
    date: '2026-06-14',
    time: '23:00',
    venue: 'Estadio BBVA, Monterrey',
    group: 'Grupo F',
    phase: 'grupo',
  },
  {
    id: 'gF03',
    homeTeam: 'Holanda',
    awayTeam: 'Suécia',
    homeFlag: '🇳🇱',
    awayFlag: '🇸🇪',
    date: '2026-06-20',
    time: '14:00',
    venue: 'NRG Stadium, Houston',
    group: 'Grupo F',
    phase: 'grupo',
  },
  {
    id: 'gF04',
    homeTeam: 'Tunísia',
    awayTeam: 'Japão',
    homeFlag: '🇹🇳',
    awayFlag: '🇯🇵',
    date: '2026-06-21',
    time: '01:00',
    venue: 'Estadio BBVA, Monterrey',
    group: 'Grupo F',
    phase: 'grupo',
  },
  {
    id: 'gF05',
    homeTeam: 'Japão',
    awayTeam: 'Suécia',
    homeFlag: '🇯🇵',
    awayFlag: '🇸🇪',
    date: '2026-06-25',
    time: '20:00',
    venue: 'AT&T Stadium, Dallas',
    group: 'Grupo F',
    phase: 'grupo',
  },
  {
    id: 'gF06',
    homeTeam: 'Tunísia',
    awayTeam: 'Holanda',
    homeFlag: '🇹🇳',
    awayFlag: '🇳🇱',
    date: '2026-06-25',
    time: '20:00',
    venue: 'Arrowhead Stadium, Kansas City',
    group: 'Grupo F',
    phase: 'grupo',
  },

  // ── Grupo G: Bélgica, Egito, Irã, Nova Zelândia ─────────────────────────
  {
    id: 'gG01',
    homeTeam: 'Bélgica',
    awayTeam: 'Egito',
    homeFlag: '🇧🇪',
    awayFlag: '🇪🇬',
    date: '2026-06-15',
    time: '16:00',
    venue: 'Lumen Field, Seattle',
    group: 'Grupo G',
    phase: 'grupo',
  },
  {
    id: 'gG02',
    homeTeam: 'Irã',
    awayTeam: 'Nova Zelândia',
    homeFlag: '🇮🇷',
    awayFlag: '🇳🇿',
    date: '2026-06-15',
    time: '22:00',
    venue: 'SoFi Stadium, Los Angeles',
    group: 'Grupo G',
    phase: 'grupo',
  },
  {
    id: 'gG03',
    homeTeam: 'Bélgica',
    awayTeam: 'Irã',
    homeFlag: '🇧🇪',
    awayFlag: '🇮🇷',
    date: '2026-06-21',
    time: '16:00',
    venue: 'SoFi Stadium, Los Angeles',
    group: 'Grupo G',
    phase: 'grupo',
  },
  {
    id: 'gG04',
    homeTeam: 'Nova Zelândia',
    awayTeam: 'Egito',
    homeFlag: '🇳🇿',
    awayFlag: '🇪🇬',
    date: '2026-06-21',
    time: '22:00',
    venue: 'BC Place, Vancouver',
    group: 'Grupo G',
    phase: 'grupo',
  },
  {
    id: 'gG05',
    homeTeam: 'Nova Zelândia',
    awayTeam: 'Bélgica',
    homeFlag: '🇳🇿',
    awayFlag: '🇧🇪',
    date: '2026-06-27',
    time: '00:00',
    venue: 'BC Place, Vancouver',
    group: 'Grupo G',
    phase: 'grupo',
  },
  {
    id: 'gG06',
    homeTeam: 'Egito',
    awayTeam: 'Irã',
    homeFlag: '🇪🇬',
    awayFlag: '🇮🇷',
    date: '2026-06-27',
    time: '00:00',
    venue: 'Lumen Field, Seattle',
    group: 'Grupo G',
    phase: 'grupo',
  },

  // ── Grupo H: Espanha, Uruguai, Arábia Saudita, Cabo Verde ───────────────
  {
    id: 'gH01',
    homeTeam: 'Espanha',
    awayTeam: 'Cabo Verde',
    homeFlag: '🇪🇸',
    awayFlag: '🇨🇻',
    date: '2026-06-15',
    time: '13:00',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    group: 'Grupo H',
    phase: 'grupo',
  },
  {
    id: 'gH02',
    homeTeam: 'Arábia Saudita',
    awayTeam: 'Uruguai',
    homeFlag: '🇸🇦',
    awayFlag: '🇺🇾',
    date: '2026-06-15',
    time: '19:00',
    venue: 'Hard Rock Stadium, Miami',
    group: 'Grupo H',
    phase: 'grupo',
  },
  {
    id: 'gH03',
    homeTeam: 'Espanha',
    awayTeam: 'Arábia Saudita',
    homeFlag: '🇪🇸',
    awayFlag: '🇸🇦',
    date: '2026-06-21',
    time: '13:00',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    group: 'Grupo H',
    phase: 'grupo',
  },
  {
    id: 'gH04',
    homeTeam: 'Uruguai',
    awayTeam: 'Cabo Verde',
    homeFlag: '🇺🇾',
    awayFlag: '🇨🇻',
    date: '2026-06-21',
    time: '19:00',
    venue: 'Hard Rock Stadium, Miami',
    group: 'Grupo H',
    phase: 'grupo',
  },
  {
    id: 'gH05',
    homeTeam: 'Uruguai',
    awayTeam: 'Espanha',
    homeFlag: '🇺🇾',
    awayFlag: '🇪🇸',
    date: '2026-06-26',
    time: '21:00',
    venue: 'Estadio Akron, Guadalajara',
    group: 'Grupo H',
    phase: 'grupo',
  },
  {
    id: 'gH06',
    homeTeam: 'Cabo Verde',
    awayTeam: 'Arábia Saudita',
    homeFlag: '🇨🇻',
    awayFlag: '🇸🇦',
    date: '2026-06-26',
    time: '21:00',
    venue: 'NRG Stadium, Houston',
    group: 'Grupo H',
    phase: 'grupo',
  },

  // ── Grupo I: França, Senegal, Noruega, Iraque ───────────────────────────
  {
    id: 'gI01',
    homeTeam: 'França',
    awayTeam: 'Senegal',
    homeFlag: '🇫🇷',
    awayFlag: '🇸🇳',
    date: '2026-06-16',
    time: '16:00',
    venue: 'MetLife Stadium, Nova York/NJ',
    group: 'Grupo I',
    phase: 'grupo',
  },
  {
    id: 'gI02',
    homeTeam: 'Iraque',
    awayTeam: 'Noruega',
    homeFlag: '🇮🇶',
    awayFlag: '🇳🇴',
    date: '2026-06-16',
    time: '19:00',
    venue: 'Gillette Stadium, Boston',
    group: 'Grupo I',
    phase: 'grupo',
  },
  {
    id: 'gI03',
    homeTeam: 'França',
    awayTeam: 'Iraque',
    homeFlag: '🇫🇷',
    awayFlag: '🇮🇶',
    date: '2026-06-22',
    time: '18:00',
    venue: 'Lincoln Financial Field, Filadélfia',
    group: 'Grupo I',
    phase: 'grupo',
  },
  {
    id: 'gI04',
    homeTeam: 'Noruega',
    awayTeam: 'Senegal',
    homeFlag: '🇳🇴',
    awayFlag: '🇸🇳',
    date: '2026-06-22',
    time: '21:00',
    venue: 'MetLife Stadium, Nova York/NJ',
    group: 'Grupo I',
    phase: 'grupo',
  },
  {
    id: 'gI05',
    homeTeam: 'Noruega',
    awayTeam: 'França',
    homeFlag: '🇳🇴',
    awayFlag: '🇫🇷',
    date: '2026-06-27',
    time: '16:00',
    venue: 'Gillette Stadium, Boston',
    group: 'Grupo I',
    phase: 'grupo',
  },
  {
    id: 'gI06',
    homeTeam: 'Senegal',
    awayTeam: 'Iraque',
    homeFlag: '🇸🇳',
    awayFlag: '🇮🇶',
    date: '2026-06-27',
    time: '16:00',
    venue: 'BMO Field, Toronto',
    group: 'Grupo I',
    phase: 'grupo',
  },

  // ── Grupo J: Argentina, Argélia, Áustria, Jordânia ──────────────────────
  {
    id: 'gJ01',
    homeTeam: 'Argentina',
    awayTeam: 'Argélia',
    homeFlag: '🇦🇷',
    awayFlag: '🇩🇿',
    date: '2026-06-16',
    time: '22:00',
    venue: 'Arrowhead Stadium, Kansas City',
    group: 'Grupo J',
    phase: 'grupo',
  },
  {
    id: 'gJ02',
    homeTeam: 'Áustria',
    awayTeam: 'Jordânia',
    homeFlag: '🇦🇹',
    awayFlag: '🇯🇴',
    date: '2026-06-17',
    time: '01:00',
    venue: "Levi's Stadium, San Francisco",
    group: 'Grupo J',
    phase: 'grupo',
  },
  {
    id: 'gJ03',
    homeTeam: 'Argentina',
    awayTeam: 'Áustria',
    homeFlag: '🇦🇷',
    awayFlag: '🇦🇹',
    date: '2026-06-22',
    time: '14:00',
    venue: 'AT&T Stadium, Dallas',
    group: 'Grupo J',
    phase: 'grupo',
  },
  {
    id: 'gJ04',
    homeTeam: 'Jordânia',
    awayTeam: 'Argélia',
    homeFlag: '🇯🇴',
    awayFlag: '🇩🇿',
    date: '2026-06-23',
    time: '00:00',
    venue: "Levi's Stadium, San Francisco",
    group: 'Grupo J',
    phase: 'grupo',
  },
  {
    id: 'gJ05',
    homeTeam: 'Argélia',
    awayTeam: 'Áustria',
    homeFlag: '🇩🇿',
    awayFlag: '🇦🇹',
    date: '2026-06-27',
    time: '23:00',
    venue: 'Arrowhead Stadium, Kansas City',
    group: 'Grupo J',
    phase: 'grupo',
  },
  {
    id: 'gJ06',
    homeTeam: 'Jordânia',
    awayTeam: 'Argentina',
    homeFlag: '🇯🇴',
    awayFlag: '🇦🇷',
    date: '2026-06-27',
    time: '23:00',
    venue: 'AT&T Stadium, Dallas',
    group: 'Grupo J',
    phase: 'grupo',
  },

  // ── Grupo K: Portugal, Uzbequistão, Colômbia, Congo DR ──────────────────
  {
    id: 'gK01',
    homeTeam: 'Portugal',
    awayTeam: 'Congo DR',
    homeFlag: '🇵🇹',
    awayFlag: '🇨🇩',
    date: '2026-06-17',
    time: '14:00',
    venue: 'NRG Stadium, Houston',
    group: 'Grupo K',
    phase: 'grupo',
  },
  {
    id: 'gK02',
    homeTeam: 'Uzbequistão',
    awayTeam: 'Colômbia',
    homeFlag: '🇺🇿',
    awayFlag: '🇨🇴',
    date: '2026-06-17',
    time: '23:00',
    venue: 'Estadio Azteca, Cidade do México',
    group: 'Grupo K',
    phase: 'grupo',
  },
  {
    id: 'gK03',
    homeTeam: 'Portugal',
    awayTeam: 'Uzbequistão',
    homeFlag: '🇵🇹',
    awayFlag: '🇺🇿',
    date: '2026-06-23',
    time: '14:00',
    venue: 'NRG Stadium, Houston',
    group: 'Grupo K',
    phase: 'grupo',
  },
  {
    id: 'gK04',
    homeTeam: 'Colômbia',
    awayTeam: 'Congo DR',
    homeFlag: '🇨🇴',
    awayFlag: '🇨🇩',
    date: '2026-06-23',
    time: '23:00',
    venue: 'Estadio Akron, Guadalajara',
    group: 'Grupo K',
    phase: 'grupo',
  },
  {
    id: 'gK05',
    homeTeam: 'Colômbia',
    awayTeam: 'Portugal',
    homeFlag: '🇨🇴',
    awayFlag: '🇵🇹',
    date: '2026-06-27',
    time: '20:30',
    venue: 'Hard Rock Stadium, Miami',
    group: 'Grupo K',
    phase: 'grupo',
  },
  {
    id: 'gK06',
    homeTeam: 'Congo DR',
    awayTeam: 'Uzbequistão',
    homeFlag: '🇨🇩',
    awayFlag: '🇺🇿',
    date: '2026-06-27',
    time: '20:30',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    group: 'Grupo K',
    phase: 'grupo',
  },

  // ── Grupo L: Inglaterra, Croácia, Gana, Panamá ──────────────────────────
  {
    id: 'gL01',
    homeTeam: 'Inglaterra',
    awayTeam: 'Croácia',
    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    awayFlag: '🇭🇷',
    date: '2026-06-17',
    time: '17:00',
    venue: 'AT&T Stadium, Dallas',
    group: 'Grupo L',
    phase: 'grupo',
  },
  {
    id: 'gL02',
    homeTeam: 'Gana',
    awayTeam: 'Panamá',
    homeFlag: '🇬🇭',
    awayFlag: '🇵🇦',
    date: '2026-06-17',
    time: '20:00',
    venue: 'BMO Field, Toronto',
    group: 'Grupo L',
    phase: 'grupo',
  },
  {
    id: 'gL03',
    homeTeam: 'Inglaterra',
    awayTeam: 'Gana',
    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    awayFlag: '🇬🇭',
    date: '2026-06-23',
    time: '17:00',
    venue: 'Gillette Stadium, Boston',
    group: 'Grupo L',
    phase: 'grupo',
  },
  {
    id: 'gL04',
    homeTeam: 'Panamá',
    awayTeam: 'Croácia',
    homeFlag: '🇵🇦',
    awayFlag: '🇭🇷',
    date: '2026-06-23',
    time: '20:00',
    venue: 'BMO Field, Toronto',
    group: 'Grupo L',
    phase: 'grupo',
  },
  {
    id: 'gL05',
    homeTeam: 'Panamá',
    awayTeam: 'Inglaterra',
    homeFlag: '🇵🇦',
    awayFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: '2026-06-27',
    time: '18:00',
    venue: 'MetLife Stadium, Nova York/NJ',
    group: 'Grupo L',
    phase: 'grupo',
  },
  {
    id: 'gL06',
    homeTeam: 'Croácia',
    awayTeam: 'Gana',
    homeFlag: '🇭🇷',
    awayFlag: '🇬🇭',
    date: '2026-06-27',
    time: '18:00',
    venue: 'Lincoln Financial Field, Filadélfia',
    group: 'Grupo L',
    phase: 'grupo',
  },
]

// ── Helpers ────────────────────────────────────────────────────────────────

/** Retorna times agrupados por grupo, derivado dos jogos cadastrados. */
export function getTeamsByGroup(): Record<string, Array<{ name: string; flag: string }>> {
  const groups: Record<string, Map<string, string>> = {}
  GAMES.filter(g => g.phase === 'grupo').forEach(game => {
    if (!groups[game.group]) groups[game.group] = new Map()
    groups[game.group].set(game.homeTeam, game.homeFlag)
    groups[game.group].set(game.awayTeam, game.awayFlag)
  })
  return Object.fromEntries(
    Object.entries(groups)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([group, teamsMap]) => [
        group,
        Array.from(teamsMap.entries()).map(([name, flag]) => ({ name, flag })),
      ])
  )
}

/** Retorna um map de nome → emoji da bandeira para lookup rápido. */
export function getTeamFlagMap(): Record<string, string> {
  const map: Record<string, string> = {}
  GAMES.forEach(game => {
    map[game.homeTeam] = game.homeFlag
    map[game.awayTeam] = game.awayFlag
  })
  return map
}

/** Retorna todos os times em ordem alfabética. */
export function getAllTeams(): Array<{ name: string; flag: string }> {
  const teams = new Map<string, string>()
  GAMES.forEach(game => {
    teams.set(game.homeTeam, game.homeFlag)
    teams.set(game.awayTeam, game.awayFlag)
  })
  return Array.from(teams.entries())
    .map(([name, flag]) => ({ name, flag }))
    .sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'))
}
